adds comments for each article
ConnorK519/fe-nc-news pull request #4
Opened 2023-07-18 14:30 UTC by ConnorK519

2023-07-18 14:49 UTC, NRMSMITH requested changes
A couple of things to consider :)

2023-07-18 14:49 UTC, NRMSMITH commented on src/components/CommentList.jsx
> +  return (
Waht would you return if there were no comments?

2023-07-18 14:49 UTC, NRMSMITH commented on src/api.js
> +  return newsApi.get(`/articles/${key}/comments`);
I think perhaps you should be finishing the promise here and _then_ returning the data formatted, rather than returning the promise.

2023-07-19 09:21 UTC, itskatherine approved these changes
Nice stuff Connor, it's good to merge ⭐

2023-07-19 09:22 UTC, merged