Fe news8
ConnorK519/fe-nc-news pull request #6
Opened 2023-07-20 15:08 UTC by ConnorK519

2023-07-20 15:38 UTC, Jodiech requested changes
Hey 👋 nice work on this ticket! There are a few comments dotted around for you to take a look at. Please implement something to prevent a user from posting multiple times! Please resubmit when you're ready and give us a shout if you need anything 👍

2023-07-20 15:38 UTC, Jodiech commented on src/components/CreateComment.jsx
> +      </form>
Currently, I can click the post button multiple times, is there a way you can add some validation to stop a user from posting multiple blank comments?

2023-07-20 15:38 UTC, Jodiech commented on src/components/CreateComment.jsx
> +  };
Don't forget to add some error handling here 👀

2023-07-20 15:38 UTC, Jodiech commented on src/components/CreateComment.jsx
> +          <textarea
Nice use of textarea here 👍

2023-07-21 08:41 UTC, B7Bprog requested changes
Hey Connor, very nice work on this one! 

Please make sure that the 'Post' button in disabled for the time of posting so it can't be clicked multiple times for the same comment and won't post it many times. 
Also a message that the comment is being posted would be nice too. (In case of a slow connection.)

Please try to implement these, then you can merge your code. 👍

2023-07-21 09:19 UTC, merged